# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a 10 digit phone number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.Choice')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-is_open', 'rank', 'date_close', 'date_created')},
        ),
        migrations.AddField(
            model_name='poll',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='polls_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(default='secret :)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a 10 digit phone number', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='mobile',
            field=models.CharField(default='secret :)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a 10 digit phone number', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Video Title'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video',
            field=models.CharField(max_length=11, verbose_name='Youtube Video ID'),
        ),
    ]
