# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, verbose_name='Ends on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(verbose_name='Starts on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Starts at'),
        ),
    ]
