# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 10:27
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160722_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image_file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='main/images/'),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='image_file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='main/images/'),
        ),
    ]
