# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160713_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-is_open', 'rank', 'date_closed', 'date_created')},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='date_close',
            new_name='date_closed',
        ),
    ]
