# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_choice_chosen_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('is_open', 'rank', 'date_closed', 'date_created')},
        ),
    ]
