# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 15:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20160718_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a 10 digit value', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='classes',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_start', '-time_start')},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('is_open', 'rank', '-date_close', '-date_open')},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='date_closed',
            new_name='date_close',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='date_created',
            new_name='date_open',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='is_multi_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a 10 digit value', regex='^\\d{10}$')], verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.Poll'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video id', regex='^[a-zA-Z0-9_-]{11}$')], verbose_name='YouTube Video ID'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='main.UserProfile'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='main.UserProfile'),
        ),
    ]
