# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='total_vote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
