# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('rank', models.IntegerField(blank=True, default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.UserProfile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='categories.Category')),
            ],
            options={
                'ordering': ('-rank', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('announcement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_files', to='announcements.Announcement')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('image_file', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_links', to='announcements.Announcement')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Video Title')),
                ('youtube_video', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video id', regex='^[a-zA-Z0-9_-]{11}$')], verbose_name='YouTube Video ID')),
                ('announcement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_videos', to='announcements.Announcement')),
            ],
        ),
    ]
